# Generated by Django 4.2.7 on 2023-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20200118_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='State_Medical_Council',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='qualification',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rating',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='registration_no',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='year_of_registration',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='mobile_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
